### ISSUE TITLE
Duplicate logarithm in `seh_frag_moo`

### ISSUE THREAD

**Issue by swansonk14** [recursionpharma/gflownet#113]
I have been working with the `seh_frag_moo.py` script, but I noticed what looks like a bug in the computation of the log reward.

In the `SEHMOOTask` class, the function `cond_info_to_logreward` first calls `self.pref_cond.transform`, which runs `scalar_logreward = (flat_reward * cond_info["preferences"]).sum(1).clamp(min=1e-30).log()` in the `MultiObjectiveWeightedPreferences` class, thereby taking a logarithm of the rewards.

Then, two lines later, `cond_info_to_logreward` calls `self.temperature_conditional.transform`, which runs `scalar_logreward = linear_reward.squeeze().clamp(min=1e-30).log()` in the `TemperatureConditional` class, thereby taking a second logarithm since the `linear_reward` variable actually holds the `scalar_logreward` value from the previous function call.

Since the first logarithm generally produces negative numbers, the second call clamps all these negatives to `1e-30` and then takes the log of that, giving `-4144.6533` as the reward for every molecule.

Should one of these clamp & logarithm operations be removed to prevent the double logarithm?

**Comment by bengioe** [comment]
Hi @swansonk14, thank you for pointing this out. This bug was fixed in a branch which seemingly was never merged, my apologies!

**Comment by bengioe** [comment]
Fixed by #117
