### ISSUE TITLE
Potential modification of flat_rewards after batch-creation

### ISSUE THREAD

**Issue by julienroyd** [recursionpharma/gflownet#61]
Experiments using a ReplayBuffer have lead to surprising results where the model would be incapable to learn if our list of `flat_rewards` (tensors of shape (2,) ) would be stacked into a tensor of shape (batch, 2) before being pushed in the buffer. We were able to fix this issue by creating a copy of each item pushed into the replay buffer (note: only copying `flat_rewards` may have been required).

- Code state with the bug ([commit 6a1b7b0](https://github.com/recursionpharma/gflownet/commit/6a1b7d062e8ca7ec729ca8202c3f7950f18af055))
- Fix ([commit 8e1163a](https://github.com/recursionpharma/gflownet/commit/8e1163a4fbac9adfc28e286569382386dc8e738d))

Our hypothesis is that `flat_rewards` (and potentially other tensors) are modified after the batch is created, which was not harmful when discarding the batch after the parameter update (on-policy) but became harmful when this modification caused the `flat_rewards` in the replay buffer to also be modified which would cause the model to train on wrong trajectory-reward pairs when this trajectory would be re-sampled from the buffer later on. It could be worth identifying what operation caused the buffer data to change to validate that this operation is intentional and should indeed occur.

**Comment by bengioe** [comment]
Seems to have been fixed by #121 . We were doing in-place modification through sliced tensors (which I didn't think was possible!) of the original data rather than creating new tensors.
